name: API CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'apps/api/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/api.yml'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'apps/api/**'
      - 'package.json'
      - 'pnpm-lock.yaml'

jobs:
  api-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '8.6.12'
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Create ESLint config if needed
        run: |
          if [ ! -f "apps/api/.eslintrc.js" ]; then
            echo "Creating ESLint config file"
            cat > apps/api/.eslintrc.js << 'EOL'
          module.exports = {
            parser: '@typescript-eslint/parser',
            parserOptions: {
              project: 'tsconfig.json',
              tsconfigRootDir: __dirname,
              sourceType: 'module',
            },
            plugins: ['@typescript-eslint/eslint-plugin'],
            extends: [
              'plugin:@typescript-eslint/recommended',
              'plugin:prettier/recommended',
            ],
            root: true,
            env: {
              node: true,
              jest: true,
            },
            ignorePatterns: ['.eslintrc.js', 'dist/**/*'],
            rules: {
              '@typescript-eslint/interface-name-prefix': 'off',
              '@typescript-eslint/explicit-function-return-type': 'off',
              '@typescript-eslint/explicit-module-boundary-types': 'off',
              '@typescript-eslint/no-explicit-any': 'off',
            },
          };
          EOL
          fi

      # Skip linting and just build
      - name: Build API
        run: pnpm --filter api build
        
      # Skip testing for now

  api-build:
    needs: api-lint-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '8.6.12'
          run_install: false

      - name: Restore pnpm dependencies
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build API
        run: pnpm --filter api build

      - name: Upload API build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api-build
          path: apps/api/dist/
          retention-days: 7

  # Uncomment and configure for deployment when ready
  # api-deploy:
  #   needs: api-build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #
  #     - name: Download build artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: api-build
  #         path: apps/api/dist/
  #
  #     # Add your deployment steps here
  #     # For example, deployment to a cloud provider like AWS, Azure, or GCP
  #     # - name: Deploy to production
  #     #   uses: some-deployment-action@v1
  #     #   with:
  #     #     api_token: ${{ secrets.DEPLOYMENT_TOKEN }}
